version: "3.3"
services:
  frontend:
    build: ./frontend
    hostname: frontend
    ports:
      - 8020:80
    networks:
      - Equipment_tree
  
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8021:8000
    networks:
      - Equipment_tree

  db:
    image: postgres:12-alpine
    hostname: db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: django_api
      POSTGRES_PASSWORD: Aa12345!
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - Equipment_tree
  
  adminer:
    image: adminer
    ports:
      - 8022:8080
    networks:
      - Equipment_tree

networks:
  Equipment_tree: