# Generated by Django 4.1.5 on 2023-02-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstancesElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=40)),
                ('kks', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Серийные номера элементов',
                'verbose_name_plural': 'Серийные номера элементов',
            },
        ),
        migrations.CreateModel(
            name='StructurElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_num', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Элементы конструкции',
                'verbose_name_plural': 'Элементы конструкции',
            },
        ),
        migrations.CreateModel(
            name='StructurElementsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=30, unique=True, verbose_name='Краткое наименование')),
                ('name', models.CharField(default='<django.db.models.fields.CharField>', max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Типы элементов конструкции',
                'verbose_name_plural': 'Типы элементов конструкции',
            },
        ),
        migrations.CreateModel(
            name='TypeConTreeStructur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=20, unique=True)),
                ('name', models.CharField(default='<django.db.models.fields.CharField>', max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Типы связей в дереве',
                'verbose_name_plural': 'Типы связей в дереве',
            },
        ),
        migrations.CreateModel(
            name='TreeStructur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_in_Objects', to='objects.structurelements')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_in_Objects', to='objects.structurelements')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.typecontreestructur')),
            ],
            options={
                'verbose_name': 'Конструктивное дерево',
                'verbose_name_plural': 'Конструктивное дерево',
            },
        ),
        migrations.CreateModel(
            name='TreeElemrnts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='objects.instanceselement')),
                ('parent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='objects.instanceselement')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.typecontreestructur')),
            ],
            options={
                'verbose_name': 'Дерево оборудования',
                'verbose_name_plural': 'Дерево оборудования',
            },
        ),
        migrations.AddField(
            model_name='structurelements',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_type', to='objects.structurelementstypes'),
        ),
        migrations.AddField(
            model_name='instanceselement',
            name='structur_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.structurelements'),
        ),
    ]
