# Generated by Django 4.1.5 on 2023-01-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_types',
            name='short_title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='tree_types_connect',
            name='short_title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='object_types',
            name='title',
            field=models.CharField(default=models.CharField(default='', max_length=20, unique=True), max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='tree_types_connect',
            name='title',
            field=models.CharField(default=models.CharField(default='', max_length=20, unique=True), max_length=70, unique=True),
        ),
    ]
