# Generated by Django 4.1.5 on 2023-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurelementstypes',
            name='name',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='structurelementstypes',
            name='short_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='typecontreestructur',
            name='name',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='typecontreestructur',
            name='short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
