# Generated by Django 4.1.5 on 2023-02-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_structurelementstypes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceselement',
            name='kks',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='treeelemrnts',
            name='parent',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='objects.instanceselement'),
        ),
    ]
